### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by gousiqi** [alexandor91/se3-equi-graph-registration#1]
Hello！Thanks for sharing the code. I would like to ask a question about the dataset. Are the datasets you provide complete? When I run the code, I encounter the following problem：
Traceback (most recent call last):
  File "train_egnn.py", line 1007, in <module>
    train_model(cross_attention_model, train_loader, val_loader, num_epochs=num_epochs, \
  File "train_egnn.py", line 909, in train_model
    train_loss = train_one_epoch(model, train_loader, optimizer, device, use_pointnet, log_interval, beta)
  File "train_egnn.py", line 624, in train_one_epoch
    for batch_idx, (corr, labels, src_pts, tar_pts, src_features, tgt_features, gt_pose) in enumerate(dataloader):
  File "/home/swin/anaconda3/envs/se3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 634, in __next__
    data = self._next_data()
  File "/home/swin/anaconda3/envs/se3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 678, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/swin/anaconda3/envs/se3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/swin/anaconda3/envs/se3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/swin/gsq/se3-equi-graph-registration-main/datasets/ThreeDMatch.py", line 344, in __getitem__
    pos_sampled = np.random.choice(pos_indices, num_pos, replace=True)
  File "mtrand.pyx", line 934, in numpy.random.mtrand.RandomState.choice
ValueError: 'a' cannot be empty unless no samples are taken

thanks a lot

**Comment by alexandor91** [comment]
I double checked the dataset, it is processed with all valid pairs, the error issue is coming from a valid length check in dataloader, now it is fixed, please pull the latest commit, thanks for point out the error.

**Comment by alexandor91** [comment]
One more thing to the training of custom dataset training, you can set "use_pointnet"  flag in the train model code to true, so that the model will train the model in end2end way from input point cloud scan pair to feature descriptor extraction, and until to equi-gnn regression, as custom dataset scenes may have some gap to indoor 3D Match or KITTI outdoor datasets. But indeed some more training time and tuning of layer hyper-params may be needed for this end2end training, and we also recommend you to use pre-trained  [PointTransformerV2](https://github.com/Pointcept/PointTransformerV2), [PointTransformerV3](https://github.com/Pointcept/PointTransformerV3), the point transformer can be used as encoder for point feature descriptor extraction, to replace pointnet encoder in the code. By using the pre-trained -point transformer encoder weights fine-tuned on custom dataset you can mitigate the data gap, and it helps to converge fast based on our recent tests.
